import { useEffect, useState } from "react";

import { BrainCircuit, CheckCircle2, ShieldQuestion } from "lucide-react";

import { useNavigate } from "react-router";

import ResearchPage from "../components/ResearchPage";

import { verificationItems } from "../data/verificationItems";

import {
  getActiveParticipantId,
  updateParticipantProgress,
} from "../services/sessionService";

import { getSectionResponses, saveResponse } from "../services/responseService";

const SECTION = "VERIFICATION_CHALLENGE";

function VerificationChallenge() {
  const navigate = useNavigate();

  const participantId = getActiveParticipantId();

  const [answers, setAnswers] = useState({});

  const [loading, setLoading] = useState(true);

  const [currentIndex, setCurrentIndex] = useState(0);

  const [saving, setSaving] = useState(false);

  useEffect(() => {
    async function initialize() {
      if (!participantId) {
        navigate("/consent", {
          replace: true,
        });

        return;
      }

      try {
        const stored = await getSectionResponses(participantId, SECTION);

        setAnswers(stored);

        /*
          Resume from the first unanswered item.
        */
        const firstUnanswered = verificationItems.findIndex(
          (item) => stored[`${item.id}_JUDGMENT`] === undefined,
        );

        if (firstUnanswered !== -1) {
          setCurrentIndex(firstUnanswered);
        } else {
          setCurrentIndex(verificationItems.length - 1);
        }

        await updateParticipantProgress("verification-challenge");
      } catch (error) {
        console.error(error);
      } finally {
        setLoading(false);
      }
    }

    initialize();
  }, [participantId, navigate]);

  const item = verificationItems[currentIndex];

  const judgmentKey = `${item.id}_JUDGMENT`;

  const confidenceKey = `${item.id}_CONFIDENCE`;

  const actionKey = `${item.id}_ACTION`;

  const judgment = answers[judgmentKey];

  const confidence = answers[confidenceKey];

  const action = answers[actionKey];

  const currentComplete =
    judgment !== undefined && confidence !== undefined && action !== undefined;

  async function saveAnswer(questionId, value) {
    setAnswers((current) => ({
      ...current,
      [questionId]: value,
    }));

    setSaving(true);

    try {
      await saveResponse({
        participantId,
        section: SECTION,
        questionId,
        value,
      });
    } catch (error) {
      console.error(error);
    } finally {
      setSaving(false);
    }
  }

  async function handleNext() {
    if (!currentComplete) {
      return;
    }

    if (currentIndex < verificationItems.length - 1) {
      setCurrentIndex((current) => current + 1);

      window.scrollTo({
        top: 0,
        behavior: "smooth",
      });

      return;
    }

    await updateParticipantProgress("results");

    navigate("/results");
  }

  if (loading) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-slate-950 text-slate-400">
        Loading challenge...
      </main>
    );
  }

  return (
    <ResearchPage
      title="AI Verification Challenge"
      subtitle="You will see several answers supposedly generated by an AI system. Judge each answer as you normally would."
      backTo="/cognitive-engagement"
      step={`Challenge ${currentIndex + 1}/${verificationItems.length}`}
    >
      <div className="mb-7 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5">
        <div className="flex gap-4">
          <ShieldQuestion className="shrink-0 text-amber-300" />

          <div>
            <h2 className="font-semibold text-amber-100">
              Do not assume the AI is right or wrong
            </h2>

            <p className="mt-2 text-sm leading-6 text-slate-400">
              Some answers may be accurate and others may contain mistakes.
              Respond according to what you would normally do if you encountered
              this answer while studying.
            </p>
          </div>
        </div>
      </div>

      <div className="mb-6 flex gap-2">
        {verificationItems.map((verificationItem, index) => {
          const completed =
            answers[`${verificationItem.id}_JUDGMENT`] !== undefined;

          return (
            <div
              key={verificationItem.id}
              className={`h-2 flex-1 rounded-full ${
                index === currentIndex
                  ? "bg-indigo-400"
                  : completed
                    ? "bg-emerald-500"
                    : "bg-slate-800"
              }`}
            />
          );
        })}
      </div>

      <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6">
        <div className="flex items-center justify-between gap-3">
          <span className="rounded-lg bg-slate-800 px-3 py-1 text-xs font-semibold text-slate-400">
            {item.domain}
          </span>

          {saving && <span className="text-xs text-slate-500">Saving...</span>}
        </div>

        <p className="mt-5 leading-7 text-slate-300">{item.prompt}</p>

        <div className="mt-6 rounded-xl border border-indigo-400/20 bg-indigo-400/5 p-5">
          <div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-indigo-300">
            <BrainCircuit size={16} />
            AI Response
          </div>

          <p className="leading-7 text-slate-200">{item.aiAnswer}</p>
        </div>
      </div>

      <QuestionSection title="How would you judge this AI answer?">
        <Choice
          selected={judgment === "CORRECT"}
          onClick={() => saveAnswer(judgmentKey, "CORRECT")}
        >
          The answer is correct
        </Choice>

        <Choice
          selected={judgment === "INCORRECT"}
          onClick={() => saveAnswer(judgmentKey, "INCORRECT")}
        >
          The answer contains an important error
        </Choice>

        <Choice
          selected={judgment === "UNSURE"}
          onClick={() => saveAnswer(judgmentKey, "UNSURE")}
        >
          I am not sure
        </Choice>
      </QuestionSection>

      <QuestionSection title="How confident are you in that judgment?">
        <div className="grid grid-cols-5 gap-2">
          {[1, 2, 3, 4, 5].map((value) => (
            <button
              key={value}
              type="button"
              onClick={() => saveAnswer(confidenceKey, value)}
              className={`rounded-xl border p-4 text-center transition ${
                confidence === value
                  ? "border-indigo-400 bg-indigo-500/15 text-indigo-100"
                  : "border-slate-700 bg-slate-950/30 text-slate-400 hover:border-slate-500"
              }`}
            >
              <div className="font-bold">{value}</div>

              <div className="mt-1 text-[10px] leading-4">
                {value === 1
                  ? "Very unsure"
                  : value === 5
                    ? "Very confident"
                    : ""}
              </div>
            </button>
          ))}
        </div>
      </QuestionSection>

      <QuestionSection title="If this answer appeared while you were studying, what would you most likely do?">
        <Choice
          selected={action === "ACCEPT"}
          onClick={() => saveAnswer(actionKey, "ACCEPT")}
        >
          Accept it and continue
        </Choice>

        <Choice
          selected={action === "VERIFY"}
          onClick={() => saveAnswer(actionKey, "VERIFY")}
        >
          Verify it using another reliable source
        </Choice>

        <Choice
          selected={action === "ASK_AI"}
          onClick={() => saveAnswer(actionKey, "ASK_AI")}
        >
          Ask the AI another question about it
        </Choice>

        <Choice
          selected={action === "IGNORE"}
          onClick={() => saveAnswer(actionKey, "IGNORE")}
        >
          Ignore the answer and solve it myself
        </Choice>
      </QuestionSection>

      <button
        disabled={!currentComplete}
        onClick={handleNext}
        className="mt-8 w-full rounded-xl bg-indigo-500 px-6 py-4 font-semibold transition enabled:hover:bg-indigo-400 disabled:cursor-not-allowed disabled:opacity-40"
      >
        {currentIndex === verificationItems.length - 1
          ? "Complete Challenge"
          : "Next AI Answer"}
      </button>
    </ResearchPage>
  );
}

function QuestionSection({ title, children }) {
  return (
    <div className="mt-5 rounded-2xl border border-slate-800 bg-slate-900/70 p-6">
      <h2 className="font-medium">{title}</h2>

      <div className="mt-4 space-y-2">{children}</div>
    </div>
  );
}

function Choice({ selected, onClick, children }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex w-full items-center gap-3 rounded-xl border p-4 text-left transition ${
        selected
          ? "border-indigo-400 bg-indigo-500/15 text-indigo-100"
          : "border-slate-700 bg-slate-950/30 text-slate-300 hover:border-slate-500"
      }`}
    >
      <div
        className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-full border ${
          selected ? "border-indigo-400" : "border-slate-600"
        }`}
      >
        {selected && <div className="h-2.5 w-2.5 rounded-full bg-indigo-400" />}
      </div>

      {children}
    </button>
  );
}

export default VerificationChallenge;
